---
title: "identify_census_sample_counts_distribution"
author: "Mengyuan Shen"
date: "2025-12-23"
format:
  html:
    toc: true
    toc-depth: 2
    code-fold: true
---


# Setup
```{r eval=FALSE}
# Get sample counts summary -----------------------------------------------
library(targets)
library(dplyr)
library(stringr)
library(glue)
library(arrow)
library(tidySingleCellExperiment)
set.seed(12345)
Date <- "2025-11-08"
# Identify raw counts range from new census data
summary_store = glue::glue("/vast/scratch/users/shen.m/{Date}_census_sample_raw_counts_summary_target_store")
tar_script({
  library(dplyr)
  library(SummarizedExperiment)
  library(zellkonverter)
  library(crew)
  library(crew.cluster)
  library(duckdb)
  
  
  computing_resources = crew_controller_slurm(
    name = "elastic",
    workers = 300,
    tasks_max = 20,
    seconds_idle = 30,
    crashes_error = 10,
    options_cluster = crew_options_slurm(
      #memory_gigabytes_required = c(30, 45, 45, 90, 200, 1000, 1500), 
       memory_gigabytes_required = c(90, 130, 170, 200, 1000, 1500), 
      cpus_per_task = c(2, 2, 2, 2, 2, 2), 
      time_minutes = c(30*4, 30*4, 30*4, 60*4, 60*24, 60*24),
      verbose = T
    ))
  
  tar_option_set(
    memory = "transient",
    garbage_collection = TRUE,
    storage = "worker",
    retrieval = "worker",
    format = "qs",
    cue = tar_cue(mode = "never"),
    error = "continue",
    controller = computing_resources
  )
  
  get_sample_summary_stats <- function(files) {
    sce = readH5AD(files, reader = "R", use_hdf5 = T)
    
    if (ncol(sce) == 0) return(NULL)
    
    assay_name = sce@assays |> names() |> magrittr::extract(1)
    counts_mat = sce |> assay(assay_name) |> as.matrix()
    counts_vec = as.numeric(counts_mat)
    sample_id = basename(files)
    
    # Perform checks
    min_val = min(counts_vec, na.rm = TRUE)
    max_val = max(counts_vec, na.rm = TRUE)
    has_negative = min_val < 0
    max_gt_10 = max_val > 10
    
    # Check if all integers
    tol = 1e-5
    all_integer = all(counts_vec == floor(counts_vec), na.rm = TRUE)
       
    #should've excluded integer, but I will fix the output dataframe
    has_floating = all(abs(counts_vec - round(counts_vec)) < tol, na.rm = TRUE)
    #has_floating = !all_integer && all(abs(counts_vec - round(counts_vec)) < tol, na.rm = TRUE)
    
    tbl = tibble::tibble(
      sample_id = sample_id,
      min_val = min_val,
      max_val = max_val,
      has_negative = has_negative,
      max_gt_10 = max_gt_10,
      all_integer = all_integer,
      has_floating = has_floating,
      n_cells = ncol(counts_mat),
      n_genes = nrow(counts_mat)
    )
    
    tbl = tbl |> left_join(
      tbl(
        dbConnect(duckdb::duckdb(), dbdir = ":memory:"),
        sql("SELECT * FROM read_parquet('/vast/projects/cellxgene_curated/metadata_cellxgenedp_Jan_2026/2025-11-08_census_samples_to_download.parquet')")
      ) |> select(-observation_joinid, list_length) |> 
        distinct() |> mutate(sample_id  = paste0(sample_id, ".h5ad")) |> collect(),
      by = "sample_id",
      copy = T
    )
    
    tbl
  }
  
  
  list(
    tar_target(
      files,
      list.files("/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id//2025-11-08", full.names = T, pattern = ".h5ad$"),
      deployment = "main"
    ),
    
    # tar_target(
    #   counts_df,
    #   {
    #     sce = readH5AD(files, reader = "R", use_hdf5 = T)
    #     
    #     if (ncol(sce) == 0) return(NULL)
    #     
    #     assay_name = sce@assays |> names() |> magrittr::extract(1)
    #     sce |> assay(assay_name) |> as.numeric() |> summary() |> 
    #       tibble::enframe(name = "stat", value = "value") |> 
    #       mutate(value = as.numeric(value)) |>
    #       mutate(sample = basename(files))
    #   }
    #   ,
    #   pattern = map(files),
    #   iteration = "list"
    # ),
    # 
    # tar_target(
    #   colSums_df,
    #   {
    #     sce = readH5AD(files, reader = "R", use_hdf5 = T)
    #     
    #     if (ncol(sce) == 0) return(NULL)
    #     
    #     assay_name = sce@assays |> names() |> magrittr::extract(1)
    #     sce |> assay(assay_name) |> colSums() |> summary() |> 
    #       tibble::enframe(name = "stat", value = "value") |> 
    #       mutate(value = as.numeric(value)) |>
    #       mutate(sample = basename(files))
    #   },
    #   pattern = map(files),
    #   iteration = "list"
    # ),
    
    # Get raw counts matrix with sample_id
    tar_target(
      sample_summary_df,
      get_sample_summary_stats(files),
      pattern = map(files),
      iteration = "list"
    )
  )
}, ask = FALSE,  script = glue("{summary_store}/_targets.R"))


job::job({
  
  tar_make(
    # callr_function = NULL,
    reporter = "summary",
    script = glue("{summary_store}/_targets.R"),
    store = glue("{summary_store}/_targets")
  )
  
})

```

```{r}
plot_raw_counts_hist_pdf <- function(
    samples_to_plot,
    h5ad_dir,
    pdf_file,
    width = 8,
    height = 8,
    nrow = 3,
    ncol = 3,
    max_cells = 5e3,
    transform = c("log1p", "none"),
    hist_ylim = c(0, 1e5)
) {
  
  transform <- match.arg(transform)
  
  pdf(pdf_file, width = width, height = height)
  on.exit(dev.off(), add = TRUE)
  
  par(mfrow = c(nrow, ncol), mar = c(3, 3, 2, 1))
  
  samples_to_plot |>
    dplyr::pull(sample_id) |>
    purrr::map(
      ~ {
        sce <- zellkonverter::readH5AD(
          file = file.path(h5ad_dir, .x),
          reader = "R",
          use_hdf5 = T
        )
        
        if (ncol(sce) == 0) return(NULL)
        
        if (ncol(sce) > max_cells) {
          sce <- dplyr::sample_n(sce, max_cells)
        }
        
        assay_name <- names(SummarizedExperiment::assays(sce))[1]
        
        dataset_id <- sce |>
          dplyr::distinct(dataset_id) |>
          dplyr::pull()
        
        x <- SummarizedExperiment::assay(sce, assay_name) |>
          as.numeric()
        
        if (transform == "log1p") {
          x <- log1p(x)
        }
        
        hist(
          x,
          main = dataset_id,
          ylim = hist_ylim
        )
        
        invisible(NULL)
      },
      .progress = TRUE
    )
  
  par(mfrow = c(1, 1))
}

```

```{r eval=FALSE}
sample_summary_df = tar_read(sample_summary_df, store = glue("{summary_store}/_targets")) |> bind_rows() |>
  mutate(max_gt_20 = ifelse(max_val > 20, TRUE, FALSE)) |> 
  
  # modify dataframe because the logic was not right in targets
  mutate(has_floating = ifelse(has_floating & !all_integer, TRUE, FALSE)) 

sample_summary_df |> write_parquet("/vast/projects/cellxgene_curated/metadata_cellxgenedp_Jan_2026/sample_distribution_summary.parquet")
```

```{r echo=FALSE}
sample_summary_df = read_parquet("/vast/projects/cellxgene_curated/metadata_cellxgenedp_Jan_2026/sample_distribution_summary.parquet")
```

# Sample statstics summary
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating)
```

# Plot sample in dataset
## Row one
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating) |> slice(1)

samples_to_plot <- sample_summary_df |> filter(!all_integer, !has_negative, !max_gt_20) |> 
  arrange(n_cells) |>
  group_by(dataset_id) |>
  slice_sample(n = 1) |>
  ungroup()

```

```{r eval=FALSE}
plot_raw_counts_hist_pdf(samples_to_plot, 
                         h5ad_dir = "/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id/2025-11-08/",
                         pdf_file = "/home/users/allstaff/shen.m/projects/cellNexus/samples_pos_lt20_decimal_raw_counts_hist.pdf", 
                         transform = "none")

```


## Row two
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating) |> slice(2)
samples_to_plot <- sample_summary_df |> filter( !has_negative, max_gt_20, !all_integer, !has_floating) |> 
  arrange(n_cells) |>
  group_by(dataset_id) |>
  slice_sample(n = 6) |>
  ungroup()
```

```{r eval=FALSE}
plot_raw_counts_hist_pdf(samples_to_plot, 
                         h5ad_dir = "/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id/2025-11-08/",
                         pdf_file = "/home/users/allstaff/shen.m/projects/cellNexus/samples_pos_gt20_decimal_raw_counts_log1p_hist.pdf", 
                         transform = "log1p")
```

## Row three
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating) |> slice(3)
samples_to_plot <- sample_summary_df |> filter(!has_negative, max_gt_20, all_integer, has_floating) |> 
  arrange(n_cells) |>
  group_by(dataset_id) |>
  slice_sample(n = 3) |>
  ungroup()
```

```{r eval=FALSE}
plot_raw_counts_hist_pdf(samples_to_plot, 
                         h5ad_dir = "/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id/2025-11-08/",
                         pdf_file = "/home/users/allstaff/shen.m/projects/cellNexus/samples_pos_gt20_int_raw_counts_log1p_hist.pdf", 
                         transform = "log1p")
```

## Row four
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating) |> slice(4)
samples_to_plot <- sample_summary_df |> filter(has_negative,!max_gt_20, !all_integer, !has_floating) |> 
  arrange(n_cells) |>
  group_by(dataset_id) |>
  slice_sample(n = 2) |>
  ungroup()
```

```{r eval=FALSE}
plot_raw_counts_hist_pdf(samples_to_plot, 
                         h5ad_dir = "/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id/2025-11-08/",
                         pdf_file = "/home/users/allstaff/shen.m/projects/cellNexus/samples_neg_lt20_decimal_raw_counts_hist.pdf", 
                         transform = "none")
```

## Row five
```{r}
sample_summary_df |> dplyr::count(has_negative, max_gt_20, all_integer, has_floating) |> slice(5)
samples_to_plot <- sample_summary_df |> filter(has_negative,max_gt_20, !all_integer, !has_floating) |> 
  arrange(n_cells) |>
  group_by(dataset_id) |>
  slice_sample(n = 2) |>
  ungroup()
```


```{r eval=FALSE}
plot_raw_counts_hist_pdf(samples_to_plot, 
                         h5ad_dir = "/vast/scratch/users/shen.m/Census/split_h5ad_based_on_sample_id/2025-11-08/",
                         pdf_file = "/home/users/allstaff/shen.m/projects/cellNexus/samples_neg_gt20_decimal_raw_counts_hist.pdf", 
                         transform = "none")
```




# Final slides and decision

```{r}
#| label: display-pptx
#| echo: false
#| warning: false
#| message: false

pptx_file <- "~/projects/cellNexus/census_distribution_decision.pptx"  
pptx_file
```
